name: MC-npubreg
version: '${project.version}'
main: com.sovereigncraft.mcnpubreg.MC_npubreg
api-version: '1.20'
authors: [Sovtoshi, CappyTech]
description: A plugin to register player npub addresses to an owned and hosted domain
website: https://sovereigncraft.com
commands:
  npubreg:
    description: registers an npub against Minecraft player name
permissions:
  mcnpubreg.use:
    description: Allows use of the npubreg command
    default: op
